# Generated by Django 6.1.1 on 2026-09-27 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pipeline', 'Pipeline'), ('plugin', 'Plugin')], max_length=16)),
                ('target', models.CharField(help_text='pipeline or model name', max_length=128)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('command', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('log', models.TextField(blank=True, help_text='tail of the CLI output')),
                ('error', models.TextField(blank=True)),
                ('result_path', models.CharField(blank=True, help_text='results file, relative to the runner workdir', max_length=512)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
